version: "3"

volumes:
  database:
    driver: local
  redis:
    driver: local
  redis-config:
    driver: local

services:
  db:
    image: postgres:latest
    container_name: mchammer-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql-docker/data
  redis:
    image: redis/redis-stack:latest
    container_name: mchammer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
