# fly.toml app configuration file generated for mchammer-vanilla-ice on 2023-12-01T20:23:04-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mchammer-vanilla-ice"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  ENVIRONMENT_NAME = "vanilla-ice"
  PORT = 8080

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
