// This file is generated by npm run build:icons

export type IconName =
	| "arrow-down"
	| "arrow-up"
	| "caret-down"
	| "caret-right"
	| "caret-sort"
	| "check"
	| "circle"
	| "cross-1"
	| "dots-horizontal"
	| "eye-none"
	| "github-logo"
	| "magnifying-glass"
	| "moon"
	| "plus-circled"
	| "sun"
	| "view-vertical";
