name: PR

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          file: ./apps/mchammer-vite/Dockerfile
          tags: topplethenun/mchammer-vite:latest
